const DEMO=[
{id:'cp1',title:'Dune: Parte Due',type:'Film',year:2024,date:'2026-09-08',genres:'Fantascienza · Avventura',runtime:'2h 46m',imdb:8.8,pulse:9.2,platforms:[['Netflix','Incluso'],['Prime Video','Incluso']],free:[],desc:'Paul Atreides si unisce a Chani e ai Fremen mentre intraprende un viaggio di guerra e destino tra i deserti di Arrakis.',poster:'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg'},
{id:'cp2',title:'Fallout',type:'Serie TV',year:2024,date:'2026-09-07',genres:'Sci-Fi · Azione',runtime:'1 stagione',imdb:8.6,pulse:9.0,platforms:[['Prime Video','Incluso'],['Netflix','Disponibile']],free:[],desc:'Duecento anni dopo l’apocalisse, gli abitanti di lussuosi rifugi sono costretti a tornare in superficie.',poster:'https://image.tmdb.org/t/p/w780/dmB4dQ6n0M4p9nZq7Q7l7J5rQwC.jpg'},
{id:'cp3',title:'The Beekeeper',type:'Film',year:2024,date:'2026-09-06',genres:'Azione · Thriller',runtime:'1h 45m',imdb:7.4,pulse:8.5,platforms:[['Prime Video','Incluso']],free:[['Pluto TV','Gratis con pubblicità']],desc:'Un uomo conduce una vendetta implacabile dopo che una truffa informatica colpisce una persona a lui vicina.',poster:'https://image.tmdb.org/t/p/w780/A7EByudX0e4N1l8K8m5g3Qm2r2D.jpg'},
{id:'cp4',title:'3 Body Problem',type:'Serie TV',year:2024,date:'2026-09-05',genres:'Sci-Fi · Dramma',runtime:'1 stagione',imdb:7.6,pulse:8.4,platforms:[['Netflix','Incluso']],free:[],desc:'Un gruppo di scienziati affronta una minaccia che mette in discussione le leggi fondamentali della scienza.',poster:'https://image.tmdb.org/t/p/w780/ykZ7hlShkdT2aLQ1g5JfQm0d2Xv.jpg'},
{id:'cp5',title:'Road House',type:'Film',year:2024,date:'2026-09-04',genres:'Azione · Thriller',runtime:'2h 1m',imdb:6.8,pulse:8.1,platforms:[['Prime Video','Incluso']],free:[],desc:'Un ex combattente UFC accetta un lavoro come buttafuori in un locale delle Florida Keys.',poster:'https://image.tmdb.org/t/p/w780/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg'},
{id:'cp6',title:'Interstellar',type:'Film',year:2014,date:'2026-09-03',genres:'Sci-Fi · Dramma',runtime:'2h 49m',imdb:8.7,pulse:9.4,platforms:[['Netflix','Disponibile']],free:[['RaiPlay','Gratis']],desc:'Un gruppo di esploratori viaggia attraverso un wormhole per cercare una nuova casa per l’umanità.',poster:'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'}
];
const state={items:JSON.parse(localStorage.getItem('cp_items')||'null')||DEMO,view:'home',list:JSON.parse(localStorage.getItem('cp_list')||'[]'),seen:JSON.parse(localStorage.getItem('cp_seen')||'[]'),filters:{type:'Tutti',range:'7 giorni'},query:''};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem('cp_items',JSON.stringify(state.items));localStorage.setItem('cp_list',JSON.stringify(state.list));localStorage.setItem('cp_seen',JSON.stringify(state.seen));}
function poster(url,title){return `<img src="${url}" alt="${esc(title)}" loading="lazy" onerror="this.src='assets/poster-fallback.svg'">`}
function card(x,i){return `<article class="card" data-id="${x.id}"><div class="poster">${poster(x.poster,x.title)}${i!=null?`<span class="rank">#${i+1}</span>`:''}<span class="score"><b>★</b> ${x.imdb.toFixed(1)}</span></div><div class="card-body"><div class="card-title">${esc(x.title)}</div><div class="card-meta">${x.type} · ${x.year}</div></div></article>`}
function bindCards(){ $$('.card,.ranking-row').forEach(e=>e.onclick=()=>openDetail(e.dataset.id)); }
function home(){let top=[...state.items].sort((a,b)=>b.pulse-a.pulse).slice(0,4), recent=[...state.items].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,4);let hero=top[0];$('#view-home').innerHTML=`<div class="hero" style="--hero:url('${hero.poster}')"><div class="hero-content"><span class="eyebrow">🔥 Migliore novità</span><h1>${esc(hero.title)}</h1><div class="meta"><span class="pill">★ IMDb ${hero.imdb.toFixed(1)}</span><span class="pill">◆ Pulse ${hero.pulse.toFixed(1)}</span><span class="pill">🆕 ${daysAgo(hero.date)}</span></div><p>${esc(hero.desc)}</p><button class="btn" data-id="${hero.id}" id="heroOpen">Scopri di più</button></div></div><div class="section-head"><div><h2>Le migliori novità</h2><p>Qualità, voto e freschezza in un unico punteggio.</p></div><button class="link" data-nav="ranking">Vedi tutte →</button></div><div class="grid">${top.map((x,i)=>card(x,i)).join('')}</div><div class="section-head"><div><h2>Appena usciti</h2><p>Gli ultimi titoli entrati nell'archivio.</p></div></div><div class="grid">${recent.map(x=>card(x)).join('')}</div><div class="footer-note">Cinema Pulse v1.0 · Modalità demo pronta per collegare fonti dati autorizzate.</div>`;$('#heroOpen').onclick=()=>openDetail(hero.id);bindCards();}
function ranking(){let a=filtered().sort((a,b)=>b.pulse-a.pulse);$('#view-ranking').innerHTML=`<div class="section-head"><div><h1>Classifica</h1><p>Ordina le novità secondo il Pulse Score.</p></div></div><div class="chips">${['Tutti','Film','Serie TV'].map(v=>`<button class="chip ${state.filters.type===v?'active':''}" data-type="${v}">${v}</button>`).join('')} ${['Oggi','7 giorni','30 giorni'].map(v=>`<button class="chip ${state.filters.range===v?'active':''}" data-range="${v}">${v}</button>`).join('')}</div>${a.length?a.map((x,i)=>`<article class="ranking-row" data-id="${x.id}"><div class="rank-num">${i+1}</div><div class="mini-poster">${poster(x.poster,x.title)}</div><div><div class="row-title">${esc(x.title)}</div><div class="row-sub">${x.type} · ${x.year} · 🆕 ${daysAgo(x.date)}</div><div class="row-sub">IMDb <b>${x.imdb.toFixed(1)}</b> · Pulse <b>${x.pulse.toFixed(1)}</b></div></div><div class="score-big">${x.pulse.toFixed(1)}</div></article>`).join(''):`<div class="empty">Nessun titolo corrisponde ai filtri.</div>`}`;$$('[data-type]').forEach(b=>b.onclick=()=>{state.filters.type=b.dataset.type;ranking()});$$('[data-range]').forEach(b=>b.onclick=()=>{state.filters.range=b.dataset.range;ranking()});bindCards();}
function search(){let q=state.query.trim().toLowerCase(),a=state.items.filter(x=>!q||(`${x.title} ${x.genres} ${x.type}`).toLowerCase().includes(q));$('#view-search').innerHTML=`<h1>Cerca</h1><p class="note">Trova film, serie e generi nell'archivio.</p><div class="searchbox" style="margin:16px 0"><input id="searchInput" value="${esc(state.query)}" placeholder="Cerca film, serie, genere..."><button class="btn" id="doSearch">Cerca</button></div><div class="grid">${a.length?a.map(x=>card(x)).join(''):'<div class="empty" style="grid-column:1/-1">Nessun risultato.</div>'}</div>`;$('#searchInput').oninput=e=>{state.query=e.target.value;search()};$('#doSearch').onclick=search;bindCards();}
function listView(){let tabs=['Da vedere','Visti','Preferiti'];let ids=state.list.filter(id=>!state.seen.includes(id));let seen=state.seen;let a=state.items.filter(x=>ids.includes(x.id)),b=state.items.filter(x=>seen.includes(x.id));$('#view-list').innerHTML=`<h1>La mia lista</h1><p class="note">Salva i titoli che vuoi ricordare.</p><div class="chips"><span class="chip active">Da vedere ${a.length}</span><span class="chip">Visti ${b.length}</span></div><div class="grid">${a.length?a.map(x=>card(x)).join(''):'<div class="empty" style="grid-column:1/-1">La tua lista è vuota. Apri una scheda e premi “Aggiungi alla lista”.</div>'}</div><div class="section-head"><div><h2>Visti</h2></div></div><div class="grid">${b.length?b.map(x=>card(x)).join(''):'<div class="empty" style="grid-column:1/-1">Nessun titolo segnato come visto.</div>'}</div>`;bindCards();}
function settings(){let services=['Netflix','Prime Video','Disney+','Apple TV+','Paramount+','NOW','RaiPlay','Mediaset Infinity','Pluto TV'];let enabled=JSON.parse(localStorage.getItem('cp_services')||'{"Netflix":true,"Prime Video":true,"RaiPlay":true,"Pluto TV":true}');$('#view-settings').innerHTML=`<h1>Impostazioni</h1><p class="note">Personalizza le piattaforme che utilizzi e il comportamento dell'app.</p><div class="settings-grid" style="margin-top:18px"><div class="settings-card"><h3>I miei servizi</h3>${services.map(s=>`<div class="setting-row"><span>${esc(s)}</span><span class="switch ${enabled[s]?'on':''}" data-service="${esc(s)}"><i></i></span></div>`).join('')}</div><div class="settings-card"><h3>Preferenze</h3><div class="setting-row"><span>Mostra solo novità</span><span class="switch on"><i></i></span></div><div class="setting-row"><span>IMDb minimo</span><strong>7.5</strong></div><div class="setting-row"><span>Aggiornamento automatico</span><span class="switch on"><i></i></span></div><p class="note">L'app verifica gli aggiornamenti quando viene aperta. Il lavoro in background dipende dai limiti del dispositivo/browser.</p></div></div><div class="settings-card" style="margin-top:16px"><h3>Privacy & dati</h3><p class="note">Liste, preferenze e stato di aggiornamento sono salvati localmente nel browser. La versione demo non invia dati personali a un server.</p><button class="btn secondary" id="clearData">Cancella dati locali</button></div>`;$$('[data-service]').forEach(s=>s.onclick=()=>{enabled[s.dataset.service]=!enabled[s.dataset.service];localStorage.setItem('cp_services',JSON.stringify(enabled));settings();});$('#clearData').onclick=()=>{if(confirm('Cancellare lista e preferenze locali?')){localStorage.clear();location.reload()}}}
function openDetail(id){let x=state.items.find(z=>z.id===id);if(!x)return;let inList=state.list.includes(id),isSeen=state.seen.includes(id);$('#view-detail').innerHTML=`<button class="link" data-nav="home">← Torna indietro</button><div class="detail" style="margin-top:18px"><div class="detail-poster">${poster(x.poster,x.title)}</div><div><span class="eyebrow">${esc(x.type)} · ${x.year}</span><h1>${esc(x.title)}</h1><div class="detail-sub">${esc(x.genres)} · ${esc(x.runtime)}</div><div class="rating-boxes"><div class="rating"><strong>★ ${x.imdb.toFixed(1)}</strong><small>IMDb / 10</small></div><div class="rating"><strong>◆ ${x.pulse.toFixed(1)}</strong><small>Pulse Score / 10</small></div></div><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn" id="listBtn">${inList?'✓ Nella lista':'+ Aggiungi alla lista'}</button><button class="btn secondary" id="seenBtn">${isSeen?'✓ Visto':'Segna come visto'}</button></div><div class="detail-section"><h3>Trama</h3><p>${esc(x.desc)}</p></div><div class="detail-section"><h3>Dove guardarlo</h3><div class="providers">${x.platforms.map(p=>`<div class="provider"><b>${esc(p[0])}</b><small>${esc(p[1])}</small><div style="margin-top:9px"><button class="link watch" data-platform="${esc(p[0])}">Guarda →</button></div></div>`).join('')}${x.free.map(p=>`<div class="provider"><b>${esc(p[0])}</b><small class="free">${esc(p[1])}</small><div style="margin-top:9px"><button class="link watch" data-platform="${esc(p[0])}">Guarda gratis →</button></div></div>`).join('')}</div></div><div class="detail-section"><h3>Perché è in classifica</h3><p>Il Pulse Score combina qualità percepita, voto IMDb, freschezza e affidabilità del campione. In produzione questi dati saranno alimentati da fonti autorizzate.</p></div></div></div>`;$('#listBtn').onclick=()=>{if(inList)state.list=state.list.filter(v=>v!==id);else state.list.push(id);save();openDetail(id);toast(inList?'Rimosso dalla lista':'Aggiunto alla lista')};$('#seenBtn').onclick=()=>{if(isSeen)state.seen=state.seen.filter(v=>v!==id);else state.seen.push(id);save();openDetail(id)};$$('.watch').forEach(b=>b.onclick=()=>toast('Link provider predisposto: collega qui la destinazione ufficiale in produzione.'));show('detail');}
function filtered(){let max=state.filters.range==='Oggi'?1:state.filters.range==='30 giorni'?30:7;let now=new Date('2026-09-08T12:00:00');let a=state.items.filter(x=>{let age=Math.floor((now-new Date(x.date))/86400000);return (state.filters.type==='Tutti'||x.type===state.filters.type)&&age<=max});return a}
function daysAgo(d){let now=new Date('2026-09-08T12:00:00'),age=Math.max(0,Math.floor((now-new Date(d))/86400000));return age===0?'oggi':age===1?'1 giorno fa':`${age} giorni fa`}
function show(v){state.view=v;$$('.view').forEach(e=>e.classList.remove('active'));$('#view-'+v).classList.add('active');$$('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.nav===v));if(v==='home')home();if(v==='ranking')ranking();if(v==='search')search();if(v==='list')listView();if(v==='settings')settings();window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
async function refresh(){let b=$('#refreshBtn');b.disabled=true;b.style.opacity=.6;toast('Controllo delle novità…');await new Promise(r=>setTimeout(r,900));let before=state.items.length;let stamp=new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});localStorage.setItem('cp_updated',stamp);$('#lastUpdated').textContent=`Aggiornato alle ${stamp}`;b.disabled=false;b.style.opacity=1;render();openUpdateModal(before);}
function openUpdateModal(before){let added=state.items.length-before;$('#modalContent').innerHTML=`<span class="eyebrow">Sincronizzazione completata</span><h2 style="margin-top:8px">Tutto aggiornato ✓</h2><ul class="update-list"><li><span>Nuovi film</span><b>${Math.max(0,added)}</b></li><li><span>Nuove serie</span><b>0</b></li><li><span>Titoli aggiornati</span><b>0</b></li><li><span>Disponibilità verificate</span><b>${state.items.length}</b></li></ul><p class="note">Nella versione demo i dati sono locali. Collega un backend/provider autorizzato per ricevere le novità reali automaticamente.</p>`;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function render(){if(state.view==='home')home();else if(state.view==='ranking')ranking();else if(state.view==='search')search();else if(state.view==='list')listView();else if(state.view==='settings')settings();}
$$('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));$('#refreshBtn').onclick=refresh;$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};
let saved=localStorage.getItem('cp_updated');$('#lastUpdated').textContent=saved?`Aggiornato alle ${saved}`:'Non ancora aggiornato';show('home');
